# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a35a1ec429c4dbe104a302da0b96dd6092bacdb222dba9958e03a6f8e82281d8ffd352a6fd3ddfeaff87f6c0a6d9fc3c02401146f62c912598d8b3ed1ccaaf58

test:
  secret_key_base: 767f0dd2313ff051d9a46d68a3dd1c9e5fa1faa5c37c083e038b07d133bc146963583c80d5c596cebae5d289ba0489cd366bf01c2809441a5348528247518515

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
